const fs = require('fs')
const zlib = require('zlib')
const readStream = fs.createReadStream('test.txt')
const writeStream = fs.createWriteStream('test.txt.gz')
const gzip = zlib.createGzip()
readStream.pipe(gzip).pipe(writeStream)
console.log('file is compressed')